init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.bat
test: off
artifacts:
  - path: '**\.build\**\testResults\*testResults.xml'
    name: testResults

  - path: '**\.build\artifacts\**\*.nupkg'
    name: packages
