init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.ps1
test: off
version: 0.0.3.{build}
artifacts:
  - path: '**\temp\TestResults\*.*'
    name: testResults

  - path: 'artifacts\**\*.nupkg'
    name: packages
